### ISSUE TITLE
关于使用别的省市，有些地方不太清晰,请指教！

### ISSUE THREAD

**Issue by CNlO** [wanggang1128/WGMapKit#1]
我不太理解SVG绘制的操作方式，以及两个plist文件的结构分析，能否单独发文讲解一下，便于我们梳理和使用。

**Comment by wanggang1128** [comment]
我在文章里增加了说明，看看能否满足你https://www.jianshu.com/p/bdfd89000025

**Comment by CNlO** [comment]
感谢大大的回复！
请问大大可不可以整理一份的图文操作，主要是关于SVG生成图，以及Plist的结构解析图！
在简书中看了一段时间后，感觉流程很简洁，很多细节不清晰。主要是一下两方面：
1、SVG感觉有点迷，因为并没有使用过SVG，所以并不清楚如何生成的SVG图;2、我看了两个Plist文件，关于结构也不理解;
作为菜鸟，希望大大可以提供一份便于操作的解说文档






------------------ Original message ------------------
From: "刚"; 
Sendtime: Friday, May 10, 2019 1:14 PM
To: "wanggang1128/WGMapKit"; 
Cc: "袁亮"; "Author"; 
Subject: Re: [wanggang1128/WGMapKit] 关于使用别的省市，有些地方不太清晰,请指教！ (#1)




我在文章里增加了说明，看看能否满足你https://www.jianshu.com/p/bdfd89000025

**Comment by wanggang1128** [comment]
第一个问题：没做过没关系，你就双击打开我给提供的广东省的svg地图，里面就是代码，你把数据替换成你的数据，这样就生成了svg图；
第二个问题：看下面解释
下面是guangDongInfo.plist的生成代码
至于 guangDongPath.plist的生成代码和下面代码类似，只是元素为UIBezierPath，至于这个UIBezierPath怎么来的，是在文章中第五步得到的。
- (void)saveData{
    
    NSMutableArray *dataArr = [[NSMutableArray alloc] init];
    
    CGRect rect1 = CGRectMake(0, 151.72, 60.14, 78.28);
    NSValue *value1 = [NSValue valueWithCGRect:rect1];
    NSDictionary *dic1 = @{
                           @"name":@"湛江",
                           @"index":@(1),
                           @"rect":value1
                           };
    [dataArr addObject:dic1];
    
    CGRect rect2 = CGRectMake(28.71, 118.79, 55.98, 57.21);
    NSValue *value2 = [NSValue valueWithCGRect:rect2];
    NSDictionary *dic2 = @{
                           @"name":@"茂名",
                           @"index":@(2),
                           @"rect":value2
                           };
    [dataArr addObject:dic2];
    
    CGRect rect3 = CGRectMake(68.32, 119.79, 45.14, 50.9);
    NSValue *value3 = [NSValue valueWithCGRect:rect3];
    NSDictionary *dic3 = @{
                           @"name":@"阳江",
                           @"index":@(3),
                           @"rect":value3
                           };
    [dataArr addObject:dic3];
    
    CGRect rect4 = CGRectMake(59.21, 92.41, 60.57, 39.81);
    NSValue *value4 = [NSValue valueWithCGRect:rect4];
    NSDictionary *dic4 = @{
                           @"name":@"云浮",
                           @"index":@(4),
                           @"rect":value4
                           };
    [dataArr addObject:dic4];
    
    CGRect rect5 = CGRectMake(98.39, 112.37, 51.89, 59.25);
    NSValue *value5 = [NSValue valueWithCGRect:rect5];
    NSDictionary *dic5 = @{
                           @"name":@"江门",
                           @"index":@(5),
                           @"rect":value5
                           };
    [dataArr addObject:dic5];
    
    CGRect rect6 = CGRectMake(71.48, 47.05, 63.37, 68.77);
    NSValue *value6 = [NSValue valueWithCGRect:rect6];
    NSDictionary *dic6 = @{
                           @"name":@"肇庆",
                           @"index":@(6),
                           @"rect":value6
                           };
    [dataArr addObject:dic6];
    
    CGRect rect7 = CGRectMake(114.33, 82.02, 41.48, 39.11);
    NSValue *value7 = [NSValue valueWithCGRect:rect7];
    NSDictionary *dic7 = @{
                           @"name":@"佛山",
                           @"index":@(7),
                           @"rect":value7
                           };
    [dataArr addObject:dic7];
    
    CGRect rect8 = CGRectMake(95.24, 13.48, 82.39, 73.38);
    NSValue *value8 = [NSValue valueWithCGRect:rect8];
    NSDictionary *dic8 = @{
                           @"name":@"清远",
                           @"index":@(8),
                           @"rect":value8
                           };
    [dataArr addObject:dic8];
    
    CGRect rect9 = CGRectMake(138.01, 66.96, 45.57, 59.48);
    NSValue *value9 = [NSValue valueWithCGRect:rect9];
    NSDictionary *dic9 = @{
                           @"name":@"广州",
                           @"index":@(9),
                           @"rect":value9
                           };
    [dataArr addObject:dic9];
    
    CGRect rect10 = CGRectMake(146.19, 115.58, 22.32, 25.28);
    NSValue *value10 = [NSValue valueWithCGRect:rect10];
    NSDictionary *dic10 = @{
                            @"name":@"中山",
                            @"index":@(10),
                            @"rect":value10
                            };
    [dataArr addObject:dic10];
    
    CGRect rect11 = CGRectMake(142.1, 129.24, 56.05, 28.25);
    NSValue *value11 = [NSValue valueWithCGRect:rect11];
    NSDictionary *dic11 = @{
                            @"name":@"珠海",
                            @"index":@(11),
                            @"rect":value11
                            };
    [dataArr addObject:dic11];
    
    CGRect rect12 = CGRectMake(167.65, 112.55, 40.55, 25.74);
    NSValue *value12 = [NSValue valueWithCGRect:rect12];
    NSDictionary *dic12 = @{
                            @"name":@"深圳",
                            @"index":@(12),
                            @"rect":value12
                            };
    [dataArr addObject:dic12];
    
    CGRect rect13 = CGRectMake(161.26, 100.06, 30.5, 20.61);
    NSValue *value13 = [NSValue valueWithCGRect:rect13];
    NSDictionary *dic13 = @{
                            @"name":@"东莞",
                            @"index":@(13),
                            @"rect":value13
                            };
    [dataArr addObject:dic13];
    
    CGRect rect14 = CGRectMake(133.49, 0, 78.37, 68.59);
    NSValue *value14 = [NSValue valueWithCGRect:rect14];
    NSDictionary *dic14 = @{
                            @"name":@"韶关",
                            @"index":@(14),
                            @"rect":value14
                            };
    [dataArr addObject:dic14];
    
    CGRect rect15 = CGRectMake(173.53, 65.56, 66.53, 66.96);
    NSValue *value15 = [NSValue valueWithCGRect:rect15];
    NSDictionary *dic15 = @{
                            @"name":@"惠州",
                            @"index":@(15),
                            @"rect":value15
                            };
    [dataArr addObject:dic15];
    
    CGRect rect16 = CGRectMake(191.33, 31.06, 56.05, 67.83);
    NSValue *value16 = [NSValue valueWithCGRect:rect16];
    NSDictionary *dic16 = @{
                            @"name":@"河源",
                            @"index":@(16),
                            @"rect":value16
                            };
    [dataArr addObject:dic16];
    
    CGRect rect17 = CGRectMake(219.11, 86.16, 54.18, 36.13);
    NSValue *value17 = [NSValue valueWithCGRect:rect17];
    NSDictionary *dic17 = @{
                            @"name":@"汕尾",
                            @"index":@(17),
                            @"rect":value17
                            };
    [dataArr addObject:dic17];
    
    CGRect rect18 = CGRectMake(235.97, 24.28, 66.96, 66.08);
    NSValue *value18 = [NSValue valueWithCGRect:rect18];
    NSDictionary *dic18 = @{
                            @"name":@"梅州",
                            @"index":@(18),
                            @"rect":value18
                            };
    [dataArr addObject:dic18];
    
    CGRect rect19 = CGRectMake(247.81, 73.44, 42.41, 39.11);
    NSValue *value19 = [NSValue valueWithCGRect:rect19];
    NSDictionary *dic19 = @{
                            @"name":@"揭阳",
                            @"index":@(19),
                            @"rect":value19
                            };
    [dataArr addObject:dic19];
    
    CGRect rect20 = CGRectMake(279.25, 54.23, 34.66, 33.8);
    NSValue *value20 = [NSValue valueWithCGRect:rect20];
    NSDictionary *dic20 = @{
                            @"name":@"潮州",
                            @"index":@(20),
                            @"rect":value20
                            };
    [dataArr addObject:dic20];
    
    CGRect rect21 = CGRectMake(274.73, 78.75, 45.57, 25.51);
    NSValue *value21 = [NSValue valueWithCGRect:rect21];
    NSDictionary *dic21 = @{
                            @"name":@"汕头",
                            @"index":@(21),
                            @"rect":value21
                            };
    [dataArr addObject:dic21];
    
    NSString *document = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)[0];
    NSString *path = [document stringByAppendingPathComponent:@"guangdongInfo.plist"];
    BOOL isSucc = [NSKeyedArchiver archiveRootObject:dataArr toFile:path];
    if (isSucc) {
        NSLog(@"----成功");
    }else{
        NSLog(@"----失败");
    }
}

**Comment by CNlO** [comment]
好的！谢谢您的耐心解答，我先自己做一遍吧！



------------------ Original message ------------------
From: "刚"; 
Sendtime: Tuesday, May 14, 2019 10:53 AM
To: "wanggang1128/WGMapKit"; 
Cc: "袁亮"; "Author"; 
Subject: Re: [wanggang1128/WGMapKit] 关于使用别的省市，有些地方不太清晰,请指教！ (#1)




第一个问题：没做过没关系，你就双击打开我给提供的广东省的svg地图，里面就是代码，你把数据替换成你的数据，这样就生成了svg图；
 第二个问题：看下面解释
 下面是guangDongInfo.plist的生成代码
 至于 guangDongPath.plist的生成代码和下面代码类似，只是元素为UIBezierPath，至于这个UIBezierPath怎么来的，是在文章中第五步得到的。
  
 
(void)saveData{
 
NSMutableArray *dataArr = [[NSMutableArray alloc] init];
 
CGRect rect1 = CGRectMake(0, 151.72, 60.14, 78.28);
 NSValue *value1 = [NSValue valueWithCGRect:rect1];
 NSDictionary *dic1 = @{
 @"name":@"湛江",
 @"index":@(1),
 @"rect":value1
 };
 [dataArr addObject:dic1];
 
CGRect rect2 = CGRectMake(28.71, 118.79, 55.98, 57.21);
 NSValue *value2 = [NSValue valueWithCGRect:rect2];
 NSDictionary *dic2 = @{
 @"name":@"茂名",
 @"index":@(2),
 @"rect":value2
 };
 [dataArr addObject:dic2];
 
CGRect rect3 = CGRectMake(68.32, 119.79, 45.14, 50.9);
 NSValue *value3 = [NSValue valueWithCGRect:rect3];
 NSDictionary *dic3 = @{
 @"name":@"阳江",
 @"index":@(3),
 @"rect":value3
 };
 [dataArr addObject:dic3];
 
CGRect rect4 = CGRectMake(59.21, 92.41, 60.57, 39.81);
 NSValue *value4 = [NSValue valueWithCGRect:rect4];
 NSDictionary *dic4 = @{
 @"name":@"云浮",
 @"index":@(4),
 @"rect":value4
 };
 [dataArr addObject:dic4];
 
CGRect rect5 = CGRectMake(98.39, 112.37, 51.89, 59.25);
 NSValue *value5 = [NSValue valueWithCGRect:rect5];
 NSDictionary *dic5 = @{
 @"name":@"江门",
 @"index":@(5),
 @"rect":value5
 };
 [dataArr addObject:dic5];
 
CGRect rect6 = CGRectMake(71.48, 47.05, 63.37, 68.77);
 NSValue *value6 = [NSValue valueWithCGRect:rect6];
 NSDictionary *dic6 = @{
 @"name":@"肇庆",
 @"index":@(6),
 @"rect":value6
 };
 [dataArr addObject:dic6];
 
CGRect rect7 = CGRectMake(114.33, 82.02, 41.48, 39.11);
 NSValue *value7 = [NSValue valueWithCGRect:rect7];
 NSDictionary *dic7 = @{
 @"name":@"佛山",
 @"index":@(7),
 @"rect":value7
 };
 [dataArr addObject:dic7];
 
CGRect rect8 = CGRectMake(95.24, 13.48, 82.39, 73.38);
 NSValue *value8 = [NSValue valueWithCGRect:rect8];
 NSDictionary *dic8 = @{
 @"name":@"清远",
 @"index":@(8),
 @"rect":value8
 };
 [dataArr addObject:dic8];
 
CGRect rect9 = CGRectMake(138.01, 66.96, 45.57, 59.48);
 NSValue *value9 = [NSValue valueWithCGRect:rect9];
 NSDictionary *dic9 = @{
 @"name":@"广州",
 @"index":@(9),
 @"rect":value9
 };
 [dataArr addObject:dic9];
 
CGRect rect10 = CGRectMake(146.19, 115.58, 22.32, 25.28);
 NSValue *value10 = [NSValue valueWithCGRect:rect10];
 NSDictionary *dic10 = @{
 @"name":@"中山",
 @"index":@(10),
 @"rect":value10
 };
 [dataArr addObject:dic10];
 
CGRect rect11 = CGRectMake(142.1, 129.24, 56.05, 28.25);
 NSValue *value11 = [NSValue valueWithCGRect:rect11];
 NSDictionary *dic11 = @{
 @"name":@"珠海",
 @"index":@(11),
 @"rect":value11
 };
 [dataArr addObject:dic11];
 
CGRect rect12 = CGRectMake(167.65, 112.55, 40.55, 25.74);
 NSValue *value12 = [NSValue valueWithCGRect:rect12];
 NSDictionary *dic12 = @{
 @"name":@"深圳",
 @"index":@(12),
 @"rect":value12
 };
 [dataArr addObject:dic12];
 
CGRect rect13 = CGRectMake(161.26, 100.06, 30.5, 20.61);
 NSValue *value13 = [NSValue valueWithCGRect:rect13];
 NSDictionary *dic13 = @{
 @"name":@"东莞",
 @"index":@(13),
 @"rect":value13
 };
 [dataArr addObject:dic13];
 
CGRect rect14 = CGRectMake(133.49, 0, 78.37, 68.59);
 NSValue *value14 = [NSValue valueWithCGRect:rect14];
 NSDictionary *dic14 = @{
 @"name":@"韶关",
 @"index":@(14),
 @"rect":value14
 };
 [dataArr addObject:dic14];
 
CGRect rect15 = CGRectMake(173.53, 65.56, 66.53, 66.96);
 NSValue *value15 = [NSValue valueWithCGRect:rect15];
 NSDictionary *dic15 = @{
 @"name":@"惠州",
 @"index":@(15),
 @"rect":value15
 };
 [dataArr addObject:dic15];
 
CGRect rect16 = CGRectMake(191.33, 31.06, 56.05, 67.83);
 NSValue *value16 = [NSValue valueWithCGRect:rect16];
 NSDictionary *dic16 = @{
 @"name":@"河源",
 @"index":@(16),
 @"rect":value16
 };
 [dataArr addObject:dic16];
 
CGRect rect17 = CGRectMake(219.11, 86.16, 54.18, 36.13);
 NSValue *value17 = [NSValue valueWithCGRect:rect17];
 NSDictionary *dic17 = @{
 @"name":@"汕尾",
 @"index":@(17),
 @"rect":value17
 };
 [dataArr addObject:dic17];
 
CGRect rect18 = CGRectMake(235.97, 24.28, 66.96, 66.08);
 NSValue *value18 = [NSValue valueWithCGRect:rect18];
 NSDictionary *dic18 = @{
 @"name":@"梅州",
 @"index":@(18),
 @"rect":value18
 };
 [dataArr addObject:dic18];
 
CGRect rect19 = CGRectMake(247.81, 73.44, 42.41, 39.11);
 NSValue *value19 = [NSValue valueWithCGRect:rect19];
 NSDictionary *dic19 = @{
 @"name":@"揭阳",
 @"index":@(19),
 @"rect":value19
 };
 [dataArr addObject:dic19];
 
CGRect rect20 = CGRectMake(279.25, 54.23, 34.66, 33.8);
 NSValue *value20 = [NSValue valueWithCGRect:rect20];
 NSDictionary *dic20 = @{
 @"name":@"潮州",
 @"index":@(20),
 @"rect":value20
 };
 [dataArr addObject:dic20];
 
CGRect rect21 = CGRectMake(274.73, 78.75, 45.57, 25.51);
 NSValue *value21 = [NSValue valueWithCGRect:rect21];
 NSDictionary *dic21 = @{
 @"name":@"汕头",
 @"index":@(21),
 @"rect":value21
 };
 [dataArr addObject:dic21];
 
NSString *document = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)[0];
 NSString *path = [document stringByAppendingPathComponent:@"guangdongInfo.plist"];
 BOOL isSucc = [NSKeyedArchiver archiveRootObject:dataArr toFile:path];
 if (isSucc) {
 NSLog(@"----成功");
 }else{
 NSLog(@"----失败");
 }
 }

**Comment by CNlO** [comment]
您好，麻烦告知一下NS.data这组数据怎么得到的，没有找到方式，谢谢了！




------------------ Original message ------------------
From: "刚"; 
Sendtime: Tuesday, May 14, 2019 10:53 AM
To: "wanggang1128/WGMapKit"; 
Cc: "袁亮"; "Author"; 
Subject: Re: [wanggang1128/WGMapKit] 关于使用别的省市，有些地方不太清晰,请指教！ (#1)




第一个问题：没做过没关系，你就双击打开我给提供的广东省的svg地图，里面就是代码，你把数据替换成你的数据，这样就生成了svg图；
 第二个问题：看下面解释
 下面是guangDongInfo.plist的生成代码
 至于 guangDongPath.plist的生成代码和下面代码类似，只是元素为UIBezierPath，至于这个UIBezierPath怎么来的，是在文章中第五步得到的。
  
 
(void)saveData{
 
NSMutableArray *dataArr = [[NSMutableArray alloc] init];
 
CGRect rect1 = CGRectMake(0, 151.72, 60.14, 78.28);
 NSValue *value1 = [NSValue valueWithCGRect:rect1];
 NSDictionary *dic1 = @{
 @"name":@"湛江",
 @"index":@(1),
 @"rect":value1
 };
 [dataArr addObject:dic1];
 
CGRect rect2 = CGRectMake(28.71, 118.79, 55.98, 57.21);
 NSValue *value2 = [NSValue valueWithCGRect:rect2];
 NSDictionary *dic2 = @{
 @"name":@"茂名",
 @"index":@(2),
 @"rect":value2
 };
 [dataArr addObject:dic2];
 
CGRect rect3 = CGRectMake(68.32, 119.79, 45.14, 50.9);
 NSValue *value3 = [NSValue valueWithCGRect:rect3];
 NSDictionary *dic3 = @{
 @"name":@"阳江",
 @"index":@(3),
 @"rect":value3
 };
 [dataArr addObject:dic3];
 
CGRect rect4 = CGRectMake(59.21, 92.41, 60.57, 39.81);
 NSValue *value4 = [NSValue valueWithCGRect:rect4];
 NSDictionary *dic4 = @{
 @"name":@"云浮",
 @"index":@(4),
 @"rect":value4
 };
 [dataArr addObject:dic4];
 
CGRect rect5 = CGRectMake(98.39, 112.37, 51.89, 59.25);
 NSValue *value5 = [NSValue valueWithCGRect:rect5];
 NSDictionary *dic5 = @{
 @"name":@"江门",
 @"index":@(5),
 @"rect":value5
 };
 [dataArr addObject:dic5];
 
CGRect rect6 = CGRectMake(71.48, 47.05, 63.37, 68.77);
 NSValue *value6 = [NSValue valueWithCGRect:rect6];
 NSDictionary *dic6 = @{
 @"name":@"肇庆",
 @"index":@(6),
 @"rect":value6
 };
 [dataArr addObject:dic6];
 
CGRect rect7 = CGRectMake(114.33, 82.02, 41.48, 39.11);
 NSValue *value7 = [NSValue valueWithCGRect:rect7];
 NSDictionary *dic7 = @{
 @"name":@"佛山",
 @"index":@(7),
 @"rect":value7
 };
 [dataArr addObject:dic7];
 
CGRect rect8 = CGRectMake(95.24, 13.48, 82.39, 73.38);
 NSValue *value8 = [NSValue valueWithCGRect:rect8];
 NSDictionary *dic8 = @{
 @"name":@"清远",
 @"index":@(8),
 @"rect":value8
 };
 [dataArr addObject:dic8];
 
CGRect rect9 = CGRectMake(138.01, 66.96, 45.57, 59.48);
 NSValue *value9 = [NSValue valueWithCGRect:rect9];
 NSDictionary *dic9 = @{
 @"name":@"广州",
 @"index":@(9),
 @"rect":value9
 };
 [dataArr addObject:dic9];
 
CGRect rect10 = CGRectMake(146.19, 115.58, 22.32, 25.28);
 NSValue *value10 = [NSValue valueWithCGRect:rect10];
 NSDictionary *dic10 = @{
 @"name":@"中山",
 @"index":@(10),
 @"rect":value10
 };
 [dataArr addObject:dic10];
 
CGRect rect11 = CGRectMake(142.1, 129.24, 56.05, 28.25);
 NSValue *value11 = [NSValue valueWithCGRect:rect11];
 NSDictionary *dic11 = @{
 @"name":@"珠海",
 @"index":@(11),
 @"rect":value11
 };
 [dataArr addObject:dic11];
 
CGRect rect12 = CGRectMake(167.65, 112.55, 40.55, 25.74);
 NSValue *value12 = [NSValue valueWithCGRect:rect12];
 NSDictionary *dic12 = @{
 @"name":@"深圳",
 @"index":@(12),
 @"rect":value12
 };
 [dataArr addObject:dic12];
 
CGRect rect13 = CGRectMake(161.26, 100.06, 30.5, 20.61);
 NSValue *value13 = [NSValue valueWithCGRect:rect13];
 NSDictionary *dic13 = @{
 @"name":@"东莞",
 @"index":@(13),
 @"rect":value13
 };
 [dataArr addObject:dic13];
 
CGRect rect14 = CGRectMake(133.49, 0, 78.37, 68.59);
 NSValue *value14 = [NSValue valueWithCGRect:rect14];
 NSDictionary *dic14 = @{
 @"name":@"韶关",
 @"index":@(14),
 @"rect":value14
 };
 [dataArr addObject:dic14];
 
CGRect rect15 = CGRectMake(173.53, 65.56, 66.53, 66.96);
 NSValue *value15 = [NSValue valueWithCGRect:rect15];
 NSDictionary *dic15 = @{
 @"name":@"惠州",
 @"index":@(15),
 @"rect":value15
 };
 [dataArr addObject:dic15];
 
CGRect rect16 = CGRectMake(191.33, 31.06, 56.05, 67.83);
 NSValue *value16 = [NSValue valueWithCGRect:rect16];
 NSDictionary *dic16 = @{
 @"name":@"河源",
 @"index":@(16),
 @"rect":value16
 };
 [dataArr addObject:dic16];
 
CGRect rect17 = CGRectMake(219.11, 86.16, 54.18, 36.13);
 NSValue *value17 = [NSValue valueWithCGRect:rect17];
 NSDictionary *dic17 = @{
 @"name":@"汕尾",
 @"index":@(17),
 @"rect":value17
 };
 [dataArr addObject:dic17];
 
CGRect rect18 = CGRectMake(235.97, 24.28, 66.96, 66.08);
 NSValue *value18 = [NSValue valueWithCGRect:rect18];
 NSDictionary *dic18 = @{
 @"name":@"梅州",
 @"index":@(18),
 @"rect":value18
 };
 [dataArr addObject:dic18];
 
CGRect rect19 = CGRectMake(247.81, 73.44, 42.41, 39.11);
 NSValue *value19 = [NSValue valueWithCGRect:rect19];
 NSDictionary *dic19 = @{
 @"name":@"揭阳",
 @"index":@(19),
 @"rect":value19
 };
 [dataArr addObject:dic19];
 
CGRect rect20 = CGRectMake(279.25, 54.23, 34.66, 33.8);
 NSValue *value20 = [NSValue valueWithCGRect:rect20];
 NSDictionary *dic20 = @{
 @"name":@"潮州",
 @"index":@(20),
 @"rect":value20
 };
 [dataArr addObject:dic20];
 
CGRect rect21 = CGRectMake(274.73, 78.75, 45.57, 25.51);
 NSValue *value21 = [NSValue valueWithCGRect:rect21];
 NSDictionary *dic21 = @{
 @"name":@"汕头",
 @"index":@(21),
 @"rect":value21
 };
 [dataArr addObject:dic21];
 
NSString *document = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)[0];
 NSString *path = [document stringByAppendingPathComponent:@"guangdongInfo.plist"];
 BOOL isSucc = [NSKeyedArchiver archiveRootObject:dataArr toFile:path];
 if (isSucc) {
 NSLog(@"----成功");
 }else{
 NSLog(@"----失败");
 }
 }
